# config.yaml
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

nodes:
  - role: control-plane
    image: kindest/node:v1.29.0     # Kubernetes version for master
    extraPortMappings:
      - containerPort: 80
        hostPort: 80
        protocol: TCP
      - containerPort: 443
        hostPort: 443
        protocol: TCP

  - role: worker
    image: kindest/node:v1.29.0     # Worker node image

  - role: worker
    image: kindest/node:v1.29.0

  - role: worker
    image: kindest/node:v1.29.0

