apiVersion: v1
kind: Service
metadata:
  name: notes-app-service
  namespace: notes-app
spec:
  type: NodePort
  selector:
    app: notes-app
  ports:
    - port: 8000        # Service port inside the cluster
      targetPort: 8000  # Container port
      nodePort: 30081
