apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: autoscale
spec:
<<<<<<< HEAD
  replicas: 1
=======
  replicas: 2
>>>>>>> 26d6d17a889f82d5ec50877b45f9edb9984e0718
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: httpd:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "200m"       # 0.2 CPU per pod
              memory: "256Mi"   # 256Mi per pod
            limits:
              cpu: "400m"       # 0.4 CPU per pod
              memory: "512Mi"   # 512Mi per pod

