apiVersion: v1
kind: Service
metadata:
  name: apache-service
  namespace: autoscale
spec:
  selector:
    app: apache
  ports:
    - protocol: TCP
      port: 80          # Service port
      targetPort: 80    # Pod container port
  type: ClusterIP      # Default, internal access only
